[ru]
languageCode = 'ru'
languageDirection = 'ltr'  # Направление текста (ltr - слева направо)
languageName = 'Russian'  # Название языка
weight = 1  # Вес языка (порядок отображения, чем ниже значение, тем раньше отображается)
