# GA Tracking ID
[googleAnalytics]
  ID = "G-741E0063WM"

[instagram]
  disableInlineCSS = true

[twitter]
  disableInlineCSS = true

# comments
[disqus]
# https://gohugo.io/templates/internal/#disqus
# disqusShortname = "your-disqus-shortname"
  shortname = ''
